site_name: Pipeliner
site_url: https://ekristen.github.io/pipeliner/
site_author: Erik Kristensen
site_description: >-
  The initial goals of this project is to provide a way to run arbitrary
  pipelines of jobs in a sane and fast manor at scale.
# Repository
repo_name: ekristen/pipeliner
repo_url: https://github.com/ekristen/pipeliner
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2016 - 2021 Erik Kristensen

# Configuration
theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - render_swagger

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ekristen
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/ekristen/pipeliner/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/esotericmeans
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/erik.kristensen/

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
