concurrent = 5
check_interval = 0

[session_server]
session_timeout = 1800

[[runners]]
name = "Prometheus"
url = "http://192.168.11.103:4444"
token = "dev"
executor = "docker"
[runners.custom_build_dir]
[runners.cache]
[runners.cache.s3]
[runners.cache.gcs]
[runners.cache.azure]
[runners.docker]
tls_verify = false
image = "ubuntu:20.04"
privileged = false
disable_entrypoint_overwrite = false
oom_kill_disable = false
disable_cache = false
volumes = ["/cache"]
shm_size = 0
