name: "gorelease"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    tags:
      - "v*.*.*"

jobs:
  version:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'renovate') == false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Detect Version for Docker
        id: docker-version
        run: echo ::set-output name=VERSION::$(SEP="-" .ci/version)
      - name: Detect Version
        id: version
        run: echo ::set-output name=VERSION::$(.ci/version)
    outputs:
      docker-version: ${{ steps.docker-version.outputs.VERSION }}
      version: ${{ steps.version.outputs.VERSION }}

  goreleaser:
    runs-on: ubuntu-latest
    needs:
      - version
    env:
      SUMMARY: ${{ needs.version.outputs.version }}
      VERSION: ${{ needs.version.outputs.version }}
      OSXCROSS_DIR: /home/runner/work/osxcross
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: OSXCross for CGO Support
        run: |
          mkdir ../../osxcross
          git clone https://github.com/plentico/osxcross-target.git ../../osxcross/target
      - name: Downgrade libssl
        run: |
          echo 'deb http://security.ubuntu.com/ubuntu bionic-security main' | sudo tee -a /etc/apt/sources.list
          sudo apt update && apt-cache policy libssl1.0-dev
          sudo apt-get install libssl1.0-dev
      - name: Run GoReleaser for Tags
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
      - name: Run GoReleaser for Non-Tags
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/v') == false
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --snapshot --skip-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
      - name: Artifact Upload
        uses: actions/upload-artifact@v2
        if: startsWith(github.ref , 'refs/tags/v') == false
        with:
          name: release
          path: |
            release/*.tar.gz
            release/config.yaml
            release/checksums.txt
